"""empty message

Revision ID: 21d8eff9a161
Revises: e92461ce601f
Create Date: 2023-02-17 17:10:21.478172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d8eff9a161'
down_revision = 'e92461ce601f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_servings', sa.Integer(), nullable=True))
        batch_op.drop_column('num_of_sevings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_sevings', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('num_of_servings')

    # ### end Alembic commands ###
