"""empty message

Revision ID: 503df6d8f7e0
Revises: a82fbef716fd
Create Date: 2023-03-09 13:04:54.283496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503df6d8f7e0'
down_revision = 'a82fbef716fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
